# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit rjournal.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE,
  fig.align = "center", out.width = "100%"
)
library(couplr)
library(ggplot2)

bench     <- read.csv("data/benchmark-table.csv", stringsAsFactors = FALSE)
lalonde   <- read.csv("data/lalonde-per-covariate.csv", stringsAsFactors = FALSE)
scaling   <- read.csv("data/scaling-results.csv", stringsAsFactors = FALSE)
lazy      <- read.csv("data/scaling-lazy-results.csv", stringsAsFactors = FALSE)
couplr_ver <- as.character(utils::packageVersion("couplr"))


## ----workflow-data, echo=TRUE-------------------------------------------------
library(couplr)
data(hospital_staff)

treated <- transform(hospital_staff$nurses_extended,   id = nurse_id)
control <- transform(hospital_staff$controls_extended, id = nurse_id)


## ----workflow-match, echo=TRUE------------------------------------------------
covars <- c("age", "experience_years", "certification_level")

m <- match_couples(
  left  = treated,
  right = control,
  vars  = covars,
  auto_scale = TRUE
)
m


## ----workflow-balance, echo=TRUE----------------------------------------------
bal <- balance_diagnostics(m, treated, control, vars = covars)
balance_table(bal)


## ----workflow-join, echo=TRUE-------------------------------------------------
matched <- join_matched(m, treated, control)
dim(matched)


## ----constraints, echo=TRUE---------------------------------------------------
m_cal <- match_couples(
  treated, control, vars = covars,
  auto_scale   = TRUE,
  calipers     = list(age = 3, experience_years = 2),
  max_distance = 1.5
)
c(pairs = nrow(m_cal$pairs), unmatched_left = length(m_cal$unmatched$left))


## ----solver-basic, echo=TRUE--------------------------------------------------
set.seed(1)
cost <- matrix(sample.int(100, 25, replace = TRUE), nrow = 5)
res  <- lap_solve(cost)
res


## ----solver-duals, echo=TRUE--------------------------------------------------
d <- assignment_duals(cost)
all(outer(d$u, d$v, "+") <= cost + 1e-9)


## ----solver-kbest, echo=TRUE--------------------------------------------------
kb <- lap_solve_kbest(cost, k = 3)
tapply(kb$total_cost, kb$rank, unique)


## ----solver-bench, fig.height=6.2, fig.cap="Median wall-clock solve time against problem size for the nineteen assignment solvers in couplr, grouped by algorithm family on shared log-log axes. Seventeen solvers are timed on square integer cost matrices with entries drawn uniformly from 1 to 10,000. The two special-purpose solvers in the Other panel run on their own inputs and are not comparable to the rest: HK-01 is timed on binary cost matrices, and Brute-F only up to n = 8. The dashed grey line repeated in every panel is the automatic dispatcher on the uniform integer costs. Medians of five replicates on a single core of an Apple M4 Pro. Cubic-time and general flow solvers are capped at smaller sizes, which is why their lines end early.", fig.alt="Five panels of log-log line plots showing solve time in milliseconds against problem size n from 4 to 5000. Solve time rises with problem size in every panel. The Jonker-Volgenant panel reaches n equals 5000 in roughly one second, the fastest of the families. Auction, cost-scaling and flow-based solvers are one to three orders of magnitude slower at matched sizes and stop at n equals 1000 or 2000. The dashed dispatcher line lies on top of the fastest solver in each panel."----
fam_map <- c(
  "JV / Augmenting path"  = "JV / augmenting path",
  "Auction"               = "Auction",
  "Cost scaling"          = "Cost scaling",
  "Flow-based"            = "Flow-based",
  "Classical"             = "Other",
  "Rectangular / general" = "Other",
  "Special-purpose"       = "Other"
)

panel_levels <- c("JV / augmenting path", "Auction", "Cost scaling",
                  "Flow-based", "Other")

solvers <- bench[bench$family != "Auto", ]
solvers$panel <- factor(fam_map[solvers$family], levels = panel_levels)

auto <- bench[bench$family == "Auto", ]
auto_all <- do.call(rbind, lapply(panel_levels, function(p) {
  transform(auto, panel = factor(p, levels = panel_levels))
}))

pal <- c(
  "JV" = "#0072B2", "SAP" = "#56B4E9", "LAPMOD" = "#004E73",
  "Auction" = "#E69F00", "Auction-GS" = "#8C5200", "Auction-S" = "#F0C066",
  "CSA" = "#009E73", "Gabow-T" = "#004534", "SSAP-B" = "#66C2A5",
  "CS-flow" = "#CC79A7", "Cycle-C" = "#7B2D5E", "Push-R" = "#E5B8D4",
  "Net-S" = "#6A3D9A", "Orlin" = "#B07AA1",
  "Hungarian" = "#D55E00", "Munkres" = "#8C3B00", "Ramshaw" = "#5A4634",
  "HK-01" = "#117733", "Brute-F" = "#999933"
)

# Curves run from the lower left to the upper right on log-log axes, so the
# upper left of every panel is free for an in-panel key.
key_order <- list(
  "JV / augmenting path" = c("JV", "SAP", "LAPMOD"),
  "Auction"              = c("Auction", "Auction-GS", "Auction-S"),
  "Cost scaling"         = c("CSA", "Gabow-T", "SSAP-B"),
  "Flow-based"           = c("CS-flow", "Cycle-C", "Push-R", "Net-S", "Orlin"),
  "Other"                = c("Hungarian", "Munkres", "Ramshaw", "HK-01",
                             "Brute-F")
)
lt_pool <- c("solid", "22", "12", "4212", "62")
lt <- unlist(lapply(key_order, function(v) setNames(lt_pool[seq_along(v)], v)))
names(lt) <- unlist(key_order)

key <- do.call(rbind, lapply(names(key_order), function(p) {
  data.frame(panel = factor(p, levels = panel_levels),
             label = key_order[[p]],
             k = seq_along(key_order[[p]]) - 1,
             stringsAsFactors = FALSE)
}))
x_lim <- c(3.5, 6000)
y_lim <- c(0.008, 2e5)
lx <- log10(x_lim); ly <- log10(y_lim)
key$x    <- 10^(lx[1] + 0.05 * diff(lx))
key$xend <- 10^(lx[1] + 0.17 * diff(lx))
key$y    <- 10^(ly[2] - (0.05 + 0.085 * key$k) * diff(ly))

ggplot(solvers, aes(n, median_ms, colour = label, linetype = label)) +
  geom_line(data = auto_all, aes(n, median_ms), inherit.aes = FALSE,
            colour = "grey45", linetype = "dashed", linewidth = 0.5) +
  geom_line(linewidth = 0.6) +
  geom_segment(data = key, aes(x = x, xend = xend, y = y, yend = y,
                               colour = label, linetype = label),
               linewidth = 0.6, inherit.aes = FALSE) +
  geom_text(data = key, aes(x = xend, y = y, label = label),
            hjust = -0.15, vjust = 0.45, size = 2.4, colour = "grey15",
            inherit.aes = FALSE) +
  facet_wrap(~ panel, ncol = 2) +
  scale_x_log10(breaks = c(10, 100, 1000), limits = x_lim,
                expand = expansion(mult = c(0.02, 0.02))) +
  scale_y_log10(breaks = c(0.01, 1, 100, 10000),
                labels = c("0.01 ms", "1 ms", "100 ms", "10 s"),
                limits = y_lim, expand = expansion(mult = c(0.02, 0.02))) +
  scale_colour_manual(values = pal, guide = "none") +
  scale_linetype_manual(values = lt, guide = "none") +
  labs(x = "problem size, n", y = "median solve time") +
  theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(colour = "grey92", linewidth = 0.3),
    strip.text = element_text(face = "bold", hjust = 0),
    axis.line = element_line(colour = "grey20", linewidth = 0.4)
  )


## ----love, fig.height=3.4, fig.cap="Absolute standardised mean differences on the eight LaLonde NSW covariates, before and after one-to-one optimal Mahalanobis matching with pooled within-group covariance. couplr, MatchIt and optmatch agree to three decimal places after matching, so a single matched point is shown per covariate. The dashed line marks the conventional 0.1 threshold. The indicator for Black respondents starts far outside the plotted range at 1.757 and remains at 1.053 after matching, a residual imbalance that no one-to-one matcher can resolve on this data.", fig.alt="A dot plot with eight covariates on the vertical axis and absolute standardised mean difference on the horizontal axis. For each covariate an open circle marks the value before matching and a filled square the value after matching, joined by a grey line. Every covariate moves left toward zero. Five of the eight land below the dashed 0.1 threshold, married and 1974 earnings sit just above it near 0.12 and 0.13, and the indicator for Black respondents remains far to the right at 1.05."----
pretty <- c(age = "age", educ = "education (years)",
            race_Black = "race: Black", race_Hispanic = "race: Hispanic",
            married = "married", nodegree = "no high-school degree",
            re74 = "earnings, 1974", re75 = "earnings, 1975")
lp <- lalonde
lp$lab <- pretty[lp$covar]
lp <- lp[order(lp$unmatched), ]
lp$lab <- factor(lp$lab, levels = lp$lab)
lp$matched <- lp$couplr

long <- rbind(
  data.frame(lab = lp$lab, state = "before matching", smd = lp$unmatched),
  data.frame(lab = lp$lab, state = "after matching",  smd = lp$matched)
)
long$state <- factor(long$state, levels = c("before matching", "after matching"))

ggplot(long, aes(smd, lab, colour = state, shape = state)) +
  geom_segment(data = lp, aes(x = unmatched, xend = matched, y = lab, yend = lab),
               inherit.aes = FALSE, colour = "grey70", linewidth = 0.4) +
  geom_vline(xintercept = 0.1, linetype = "22", colour = "grey30",
             linewidth = 0.4) +
  geom_point(size = 2.4, stroke = 0.9) +
  scale_colour_manual(values = c("before matching" = "#D55E00",
                                 "after matching"  = "#0072B2"), name = NULL) +
  scale_shape_manual(values = c("before matching" = 1,
                                "after matching"  = 15), name = NULL) +
  scale_x_continuous(limits = c(-0.02, 1.85),
                     breaks = c(0, 0.1, 0.5, 1.0, 1.5)) +
  labs(x = "|standardised mean difference|", y = NULL) +
  theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(colour = "grey92", linewidth = 0.3),
    legend.position = "bottom",
    axis.line.x = element_line(colour = "grey20", linewidth = 0.4)
  )


## ----scaling, echo=FALSE------------------------------------------------------
lab <- c("167 + 333", "667 + 1,333", "1,667 + 3,333",
         "3,333 + 6,667", "6,667 + 13,333", "16,667 + 33,333")
sizes <- c(500, 2000, 5000, 10000, 20000, 50000)

fmt <- function(pkg) {
  vapply(sizes, function(n) {
    r <- scaling[scaling$n_total == n & scaling$package == pkg, ]
    if (nrow(r) == 0) return("not run")
    if (is.na(r$median_s[1])) {
      return(if (grepl("timeout", r$status[1])) "timeout" else "int overflow")
    }
    s <- r$median_s[1]
    if (s < 1) sprintf("%.0f ms", s * 1000) else sprintf("%.3g s", s)
  }, character(1))
}

tab <- data.frame(
  `Problem size` = lab,
  couplr   = fmt("couplr"),
  optmatch = fmt("optmatch"),
  MatchIt  = fmt("MatchIt"),
  check.names = FALSE
)

knitr::kable(
  tab, align = "lrrr", booktabs = TRUE,
  caption = "One-to-one optimal Mahalanobis matching, median wall-clock time by problem size. Treated to control ratio 1:2, eight covariates, pooled within-group covariance, single core with single-threaded BLAS on an Apple M4 Pro. Medians of 5, 5, 3, 3, 1 and 1 replicates for the six rows. The optmatch option max.problem.size was set to Inf for the two largest sizes. int overflow marks an integer-size overflow inside the optmatch back end reached through MatchIt; timeout marks a replicate exceeding the 300-second cap."
)


## ----capability, echo=FALSE---------------------------------------------------
cap <- data.frame(
  Feature = c("Per-variable calipers from a named vector",
              "Rectangular problems without padding",
              "Sparse cost support",
              "k-best assignments",
              "Bottleneck (minimax) assignment",
              "Rosenbaum sensitivity bounds",
              "User-selectable assignment algorithm"),
  couplr = c("yes", "yes", "yes", "yes", "yes", "yes", "19 solvers"),
  MatchIt = c("yes", "partial", "no", "no", "no", "no", "fixed"),
  optmatch = c("partial", "partial", "yes", "no", "no", "no", "fixed"),
  check.names = FALSE
)
knitr::kable(
  cap, align = "lccc", booktabs = TRUE,
  caption = "Differentiating feature coverage. partial marks a feature that is achievable but not through a first-class user-facing interface: optmatch calipers threshold one distance object at a time, so per-variable calipers require combining objects, and both alternatives handle unequal group sizes through discarding or variable-ratio designs rather than natively."
)

