# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit rjournal.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE,
  fig.align = "center", out.width = "100%",
  ## The default pdf() device draws figure text as unembedded Helvetica, so the
  ## article PDF carries font objects a reader may not have. cairo_pdf embeds
  ## the faces it draws with. The HTML build keeps its own raster device.
  dev = if (knitr::is_latex_output()) "cairo_pdf" else "png"
)
library(couplr)
library(ggplot2)

bench     <- read.csv("data/benchmark-table.csv", stringsAsFactors = FALSE)
lalonde   <- read.csv("data/lalonde-per-covariate.csv", stringsAsFactors = FALSE)
lal_obj   <- read.csv("data/lalonde-results.csv", stringsAsFactors = FALSE)
scaling   <- read.csv("data/scaling-results.csv", stringsAsFactors = FALSE)
lazy      <- read.csv("data/scaling-lazy-results.csv", stringsAsFactors = FALSE)
imp       <- read.csv("data/implicit-results.csv", stringsAsFactors = FALSE)
equiv     <- read.csv("data/implicit-equivalence.csv", stringsAsFactors = FALSE)
pth       <- read.csv("data/path-results.csv", stringsAsFactors = FALSE)
regime    <- read.csv("data/regime-verdict.csv", stringsAsFactors = FALSE)
igrid     <- read.csv("data/implicit-grid-results.csv", stringsAsFactors = FALSE)
memory    <- read.csv("data/memory-results.csv", stringsAsFactors = FALSE)
n_path_values <- pth$points[1]

## The environment block the benchmark suite writes beside its CSVs, so the
## article states the machine, the R version, the package version and the date
## its numbers were measured on rather than repeating a remembered value. The
## version is read from here and not from the rendering machine's library,
## which answers a different question from the one the sentences ask.
env_lines <- readLines("data/ENVIRONMENT.txt", warn = FALSE)
env_field <- function(key) {
  hit <- grep(paste0("^", key, "[[:space:]]"), env_lines, value = TRUE)
  if (!length(hit)) return(NA_character_)
  sub("^[^[:space:]]+[[:space:]]+([^[:space:]]+).*$", "\\1", hit[1])
}
bench_run    <- env_field("run")
bench_date   <- format(as.Date(substr(bench_run, 1, 8), "%Y%m%d"))
bench_commit <- env_field("commit")
couplr_ver   <- env_field("couplr")
bench_r <- sub("^R version ([0-9.]+).*$", "\\1",
               grep("^R version", env_lines, value = TRUE)[1])

## Timings by size for one memory mode, from the edge-generation benchmark.
imp_at <- function(mode, n, col = "elapsed_s") {
  imp[[col]][imp$memory_mode == mode & imp$n_total == n][1]
}

## Every ratio the prose states is read off the tables rather than written into
## the sentence, so a re-measurement cannot leave a stale number in the text.
scal_at <- function(pkg, n) {
  scaling$median_s[scaling$package == pkg & scaling$n_total == n][1]
}
scal_ratio <- function(n, against = "optmatch") {
  scal_at(against, n) / scal_at("couplr", n)
}
mem_at <- function(arm, n, col = "peak_rss_mb") {
  memory[[col]][memory$arm == arm & memory$n_total == n][1]
}

## The multipliers the memory guard is built on, taken from the package rather
## than repeated here, beside the peaks they were set above.
solve_factor  <- eval(formals(couplr:::estimate_dense_solve_mb)$solve_factor)
matrix_factor <- eval(formals(couplr:::estimate_dense_matrix_mb)$overhead_factor)
mem_sizes <- sort(unique(memory$n_total[memory$arm == "dense" &
                                        memory$status == "ok"]))
mem_sizes <- mem_sizes[mem_sizes >= 5000]
mem_over_matrix <- function(arm) {
  over <- vapply(mem_sizes, function(n) mem_at(arm, n, "over_baseline_mb"),
                 numeric(1))
  cells <- vapply(mem_sizes, function(n) mem_at(arm, n, "matrix_mb"), numeric(1))
  over / cells
}
and_list <- function(v) {
  if (length(v) < 2) return(paste(v))
  paste0(paste(v[-length(v)], collapse = ", "), " and ", v[length(v)])
}
mem_size_list   <- and_list(format(mem_sizes, big.mark = ",", trim = TRUE))
mem_solve_list  <- and_list(sprintf("%.1f", mem_over_matrix("dense")))
mem_matrix_list <- and_list(sprintf("%.1f", mem_over_matrix("dense_matrix")))


## ----certify, echo=TRUE-------------------------------------------------------
set.seed(2)
cost <- matrix(runif(120), nrow = 6, ncol = 20)
verify_assignment(assignment(cost), cost)


## ----solver-basic, echo=TRUE--------------------------------------------------
set.seed(1)
cost <- matrix(sample.int(100, 25, replace = TRUE), nrow = 5)
res  <- lap_solve(cost)
res


## ----solver-kbest, echo=TRUE--------------------------------------------------
kb <- lap_solve_kbest(cost, k = 3)
tapply(kb$total_cost, kb$rank, unique)


## ----workflow-match, echo=TRUE------------------------------------------------
library(couplr)
data(hospital_staff)
treated <- transform(hospital_staff$nurses_extended,   id = nurse_id)
control <- transform(hospital_staff$controls_extended, id = nurse_id)
covars  <- c("age", "experience_years", "certification_level")

m <- match_couples(treated, control, vars = covars, auto_scale = TRUE)
m$pairs[1:3, c("left_id", "right_id", "distance", ".age_diff")]


## ----constraints, echo=TRUE---------------------------------------------------
m_cal <- match_couples(treated, control, vars = covars, auto_scale = TRUE,
                       calipers = list(age = 3, experience_years = 2),
                       max_distance = 1.5)


## ----verify-flow, echo=TRUE---------------------------------------------------
prob <- list(n_nodes = 4, supply = c(2, 1, -2, -1),
             arcs = data.frame(tail = c(1, 1, 2, 2), head = c(3, 4, 3, 4),
                               lower = 0, upper = 2, cost = c(1, 3, 2, 1)))
cert <- verify_flow(c(2, 0, 0, 1), prob, potential = c(0, 0, 1, 1))
c(certified = cert$certified_optimal, gap = cert$duality_gap)


## ----implicit, echo=TRUE------------------------------------------------------
m_imp <- match_couples(treated, control, vars = covars, auto_scale = TRUE,
                       memory_mode = "implicit", certify = TRUE)
m_imp$certificate$certified_optimal
unlist(m_imp$search[c("seed_width", "n_rounds",
                      "candidate_edges", "possible_edges")])


## ----path, echo=TRUE----------------------------------------------------------
p <- match_path(treated, control, vars = covars, auto_scale = TRUE,
                vary = "max_distance", values = c(1.0, 1.2, 1.5, 2.0, 3.0))
p$path[, c("max_distance", "n_matched", "total_distance", "certified")]


## ----implicit-table, echo=FALSE-----------------------------------------------
isz  <- c(500, 2000, 5000, 10000, 20000, 50000)
ilab <- c("167 + 333", "667 + 1,333", "1,667 + 3,333",
          "3,333 + 6,667", "6,667 + 13,333", "16,667 + 33,333")

secs <- function(mode) {
  vapply(isz, function(n) {
    s <- imp_at(mode, n)
    if (is.na(s)) return("not run")
    if (s < 1) sprintf("%.0f ms", s * 1000) else sprintf("%.3g s", s)
  }, character(1))
}
share <- vapply(isz, function(n) {
  sprintf("%.2f%%", 100 * imp_at("implicit", n, "candidate_edges") /
            imp_at("implicit", n, "possible_edges"))
}, character(1))
dists <- vapply(isz, function(n) {
  sprintf("%.2f", imp_at("implicit", n, "edges_evaluated") /
            imp_at("implicit", n, "possible_edges"))
}, character(1))
rounds <- vapply(isz, function(n) {
  as.character(imp_at("implicit", n, "n_rounds"))
}, character(1))

knitr::kable(
  data.frame(`Problem size` = ilab, dense = secs("dense"), lazy = secs("lazy"),
             implicit = secs("implicit"), `Graph built` = share,
             `Distances` = dists, Rounds = rounds, check.names = FALSE),
  align = "lrrrrrr", booktabs = TRUE,
  caption = "One-to-one optimal Mahalanobis matching by memory mode, wall-clock seconds on a single core of an Apple M4 Pro. Graph built is the arcs the implicit loop ended up holding as a share of the complete problem's. Distances is its evaluations over all rounds as a multiple of the complete pair count, so a pair priced twice counts twice. All three arms were timed in one session; the dense arm was run at the four sizes where its pairing can be compared against the loop's, and the scaling table below carries dense timings at the two largest sizes. Every cell returned the same total distance."
)


## ----igrid-numbers, echo=FALSE------------------------------------------------
ig_cells   <- nrow(igrid)
ig_seeds   <- sum(igrid$seeds)
ig_rounds  <- c(min(igrid$rounds_min), max(igrid$rounds_max))
ig_graph   <- range(igrid$graph_pct_med)
ig_dist    <- range(igrid$distances_x_med)
ig_cert    <- sum(igrid$all_certified %in% TRUE)
ig_eq_den  <- sum(!is.na(igrid$equal_to_dense))
ig_eq      <- sum(igrid$equal_to_dense %in% TRUE)
ig_gap     <- max(igrid$worst_gap, na.rm = TRUE)
## "All N" only where that is what the grid did; otherwise the count is named.
ig_cert_txt <- if (ig_cert == ig_cells) {
  sprintf("All %d cells certified", ig_cells)
} else {
  sprintf("%d of the %d cells certified", ig_cert, ig_cells)
}
ig_clouds  <- igrid[igrid$sweep == "cloud", ]
ig_slow    <- ig_clouds$cloud[which.min(ig_clouds$speedup_med)]
ig_slow_x  <- min(ig_clouds$speedup_med)
ig_fast    <- ig_clouds$cloud[which.max(ig_clouds$speedup_med)]
ig_fast_x  <- max(ig_clouds$speedup_med)
## A ratio below one is the loop losing, and the sentence says so only where
## that happens rather than carrying the caveat unconditionally.
ig_note    <- if (ig_slow_x < 1) {
  ", where a ratio below one is the loop losing to the lazy path"
} else ""
## The cell built to be hostile to the loop, reported in the text beside the
## ordinary clouds so the worst case is not left as a statement about a bound.
ig_cont    <- igrid[igrid$sweep == "cloud" & igrid$cloud == "contested", ][1, ]
ig_dims    <- igrid[igrid$sweep == "dimension", ]
ig_dim_rng <- range(ig_dims$dim)


## ----memory-numbers, echo=FALSE-----------------------------------------------
mem_n <- max(memory$n_total[memory$arm == "dense" & memory$status == "ok"])
mem_lab <- sprintf("%s + %s", format(round(mem_n / 3), big.mark = ","),
                   format(mem_n - round(mem_n / 3), big.mark = ","))
mem_over <- function(arm, n = mem_n) mem_at(arm, n, "over_baseline_mb")
mem_matrix <- mem_at("dense_matrix", mem_n, "matrix_mb")
mem_ratio  <- mem_over("dense_matrix") / mem_matrix
mem_solve_ratio <- mem_over("dense") / mem_matrix


## ----path-table, echo=FALSE---------------------------------------------------
knitr::kable(
  data.frame(
    `Problem size` = ilab[match(pth$n_total, isz)],
    `As a path` = sprintf("%.3g s", pth$warm_wall),
    `Independently` = sprintf("%.3g s", pth$cold_wall),
    Ratio = sprintf("%.2fx", pth$wall_speedup),
    `Solve time` = sprintf("%.2fx", pth$speedup),
    `Rounds` = sprintf("%d / %d", pth$warm_rounds, pth$cold_rounds),
    check.names = FALSE
  ),
  align = "lrrrrr", booktabs = TRUE,
  caption = "A caliper sweep solved as one warm-started path against the same values solved independently, end-to-end wall clock for the whole sweep on a single core of an Apple M4 Pro. Solve time is the same comparison on the seconds the solver reports for itself, summed over the points, which excludes the R-level work both sides do. Rounds is the pricing rounds each side took, summed over the sweep."
)


## ----solver-bench, fig.height=4.2, fig.cap="Median wall-clock solve time against problem size for the nineteen assignment solvers in couplr, grouped by algorithm family on shared log-log axes. The two special-purpose solvers in the Other panel run on their own inputs and are not comparable to the rest: HK-01 is timed on binary cost matrices, and Brute-F only up to n = 8. The dashed grey line repeated in every panel is the automatic dispatcher on the uniform integer costs.", fig.alt="Five panels of log-log line plots showing solve time in milliseconds against problem size n from 4 to 5000. Solve time rises with problem size in every panel. The Jonker-Volgenant panel reaches n equals 5000 in roughly one second, the fastest of the families. Auction, cost-scaling and flow-based solvers are one to three orders of magnitude slower at matched sizes and stop at n equals 1000 or 2000. The dashed dispatcher line lies on top of the fastest solver in each panel."----
fam_map <- c(
  "JV / Augmenting path"  = "JV / augmenting path",
  "Auction"               = "Auction",
  "Cost scaling"          = "Cost scaling",
  "Flow-based"            = "Flow-based",
  "Classical"             = "Other",
  "Rectangular / general" = "Other",
  "Special-purpose"       = "Other"
)

panel_levels <- c("JV / augmenting path", "Auction", "Cost scaling",
                  "Flow-based", "Other")

solvers <- bench[bench$family != "Auto", ]
solvers$panel <- factor(fam_map[solvers$family], levels = panel_levels)

auto <- bench[bench$family == "Auto", ]
auto_all <- do.call(rbind, lapply(panel_levels, function(p) {
  transform(auto, panel = factor(p, levels = panel_levels))
}))

pal <- c(
  "JV" = "#0072B2", "SAP" = "#56B4E9", "SAP-D" = "#08519C",
  "LAPMOD" = "#004E73",
  "Auction" = "#E69F00", "Auction-GS" = "#8C5200", "Auction-S" = "#F0C066",
  "CSA" = "#009E73", "Gabow-T" = "#004534", "SSAP-B" = "#66C2A5",
  "CS-flow" = "#CC79A7", "Cycle-C" = "#7B2D5E", "Push-R" = "#E5B8D4",
  "Net-S" = "#6A3D9A",
  "Hungarian" = "#D55E00", "Munkres" = "#8C3B00", "Ramshaw" = "#5A4634",
  "HK-01" = "#117733", "Brute-F" = "#999933"
)

# Curves run from the lower left to the upper right on log-log axes, so the
# upper left of every panel is free for an in-panel key.
key_order <- list(
  "JV / augmenting path" = c("JV", "SAP", "SAP-D", "LAPMOD"),
  "Auction"              = c("Auction", "Auction-GS", "Auction-S"),
  "Cost scaling"         = c("CSA", "Gabow-T", "SSAP-B"),
  "Flow-based"           = c("CS-flow", "Cycle-C", "Push-R", "Net-S"),
  "Other"                = c("Hungarian", "Munkres", "Ramshaw", "HK-01",
                             "Brute-F")
)
lt_pool <- c("solid", "22", "12", "4212", "62")
lt <- unlist(lapply(key_order, function(v) setNames(lt_pool[seq_along(v)], v)))
names(lt) <- unlist(key_order)

key <- do.call(rbind, lapply(names(key_order), function(p) {
  data.frame(panel = factor(p, levels = panel_levels),
             label = key_order[[p]],
             k = seq_along(key_order[[p]]) - 1,
             stringsAsFactors = FALSE)
}))
x_lim <- c(3.5, 6000)
y_lim <- c(0.008, 2e5)
lx <- log10(x_lim); ly <- log10(y_lim)
key$x    <- 10^(lx[1] + 0.05 * diff(lx))
key$xend <- 10^(lx[1] + 0.17 * diff(lx))
key$y    <- 10^(ly[2] - (0.05 + 0.118 * key$k) * diff(ly))

ggplot(solvers, aes(n, median_ms, colour = label, linetype = label)) +
  geom_line(data = auto_all, aes(n, median_ms), inherit.aes = FALSE, colour = "grey45", linetype = "dashed", linewidth = 0.65) + geom_line(linewidth = 0.75) +
  geom_segment(data = key, aes(x = x, xend = xend, y = y, yend = y,
                               colour = label, linetype = label),
               linewidth = 0.75, inherit.aes = FALSE) +
  geom_text(data = key, aes(x = xend, y = y, label = label),
            hjust = -0.15, vjust = 0.45, size = 3.4, colour = "grey15",
            inherit.aes = FALSE) +
  facet_wrap(~ panel, ncol = 2) +
  scale_x_log10(breaks = c(10, 100, 1000), limits = x_lim,
                expand = expansion(mult = c(0.02, 0.02))) +
  scale_y_log10(breaks = c(0.01, 1, 100, 10000),
                labels = c("0.01 ms", "1 ms", "100 ms", "10 s"),
                limits = y_lim, expand = expansion(mult = c(0.02, 0.02))) +
  scale_colour_manual(values = pal, guide = "none") +
  scale_linetype_manual(values = lt, guide = "none") +
  labs(x = "problem size, n", y = "median solve time") +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(colour = "grey92", linewidth = 0.3),
    strip.text = element_text(face = "bold", hjust = 0, size = 11),
    axis.text = element_text(size = 9),
    axis.title = element_text(size = 11),
    axis.line = element_line(colour = "grey20", linewidth = 0.4)
  )


## ----regimes, echo=FALSE------------------------------------------------------
rule_lab <- c(tiny = "at most 8 by 8",
              no_cost_scale = "no cost scale to exploit",
              sparse = "more than half the entries forbidden",
              very_rectangular = "at least three columns per row",
              default = "no earlier rule applies")
by_rule <- do.call(rbind, lapply(split(regime, regime$auto_rule), function(g) {
  data.frame(
    Rule = rule_lab[g$auto_rule[1]],
    Solver = g$auto_picks[1],
    Cells = nrow(g),
    `Fastest` = sum(g$auto_picks == g$best_method),
    `Median` = sprintf("%.2fx", median(g$ratio)),
    `Worst` = sprintf("%.2fx", max(g$ratio)),
    check.names = FALSE
  )
}))
by_rule <- by_rule[order(-by_rule$Cells), ]

knitr::kable(
  by_rule, align = "llrrrr", booktabs = TRUE, row.names = FALSE,
  caption = "Each dispatch rule over the cells of the regime grid where it fired. Solver is what the rule selects. Fastest counts the cells where that solver was also the quickest of the panel. Median and worst are the time the dispatched solver took over the time the cell's fastest named solver took, so 1.00x is a rule that picked the best available solver. The large tier times a reduced panel that omits the special-purpose solvers, so a cell whose dispatched solver is not in it reads below 1.00x."
)


## ----regime-numbers, echo=FALSE-----------------------------------------------
reg_fast <- sum(regime$auto_picks == regime$best_method)
reg_def  <- regime[regime$auto_rule == "default", ]
## The two properties that used to carry rules of their own, so the text can
## say what the default costs in the regimes they were written for.
reg_rect <- reg_def[reg_def$shape %in% c("500 x 1500", "500 x 5000",
                                         "1500 x 4500", "1000 x 10000"), ]
reg_sp   <- reg_def[reg_def$pattern %in% c("random_25", "random_05",
                                           "random_01", "block_4"), ]
reg_worst <- regime[which.max(regime$ratio), ]
x <- function(v) sprintf("%.2fx", v)
## A cell has no `picked_s` exactly where the solver the rule named was not
## itself in that cell's panel, which is the large tier's reduced panel.
off_panel <- regime[is.na(regime$picked_s), ]
reg_ncs   <- regime[regime$auto_rule == "no_cost_scale", ]
ncs_in    <- reg_ncs[!is.na(reg_ncs$picked_s), ]


## ----love, fig.height=2.6, fig.pos="H", fig.cap="Absolute standardised mean differences on the eight LaLonde NSW covariates, before and after one-to-one optimal Mahalanobis matching with pooled within-group covariance. couplr, MatchIt and optmatch agree to three decimal places after matching, so a single matched point is shown per covariate. The dashed line marks the conventional 0.1 threshold. The indicator for Black respondents starts far outside the plotted range at 1.757 and remains at 1.053 after matching, a residual imbalance that no one-to-one matcher can resolve on this data.", fig.alt="A dot plot with eight covariates on the vertical axis and absolute standardised mean difference on the horizontal axis. For each covariate an open circle marks the value before matching and a filled square the value after matching, joined by a grey line. Every covariate moves left toward zero. Five of the eight land below the dashed 0.1 threshold, married and 1974 earnings sit just above it near 0.12 and 0.13, and the indicator for Black respondents remains far to the right at 1.05."----
pretty <- c(age = "age", educ = "education (years)",
            race_Black = "race: Black", race_Hispanic = "race: Hispanic",
            married = "married", nodegree = "no high-school degree",
            re74 = "earnings, 1974", re75 = "earnings, 1975")
lp <- lalonde
lp$lab <- pretty[lp$covar]
lp <- lp[order(lp$unmatched), ]
lp$lab <- factor(lp$lab, levels = lp$lab)
lp$matched <- lp$couplr

long <- rbind(
  data.frame(lab = lp$lab, state = "before matching", smd = lp$unmatched),
  data.frame(lab = lp$lab, state = "after matching",  smd = lp$matched)
)
long$state <- factor(long$state, levels = c("before matching", "after matching"))

ggplot(long, aes(smd, lab, colour = state, shape = state)) +
  geom_segment(data = lp, aes(x = unmatched, xend = matched, y = lab, yend = lab),
               inherit.aes = FALSE, colour = "grey70", linewidth = 0.4) +
  geom_vline(xintercept = 0.1, linetype = "22", colour = "grey30",
             linewidth = 0.4) +
  geom_point(size = 2.4, stroke = 0.9) +
  scale_colour_manual(values = c("before matching" = "#D55E00",
                                 "after matching"  = "#0072B2"), name = NULL) +
  scale_shape_manual(values = c("before matching" = 1,
                                "after matching"  = 15), name = NULL) +
  scale_x_continuous(limits = c(-0.02, 1.85),
                     breaks = c(0, 0.1, 0.5, 1.0, 1.5)) +
  labs(x = "|standardised mean difference|", y = NULL) +
  theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(colour = "grey92", linewidth = 0.3),
    legend.position = "bottom",
    axis.line.x = element_line(colour = "grey20", linewidth = 0.4)
  )


## ----scaling, echo=FALSE------------------------------------------------------
lab <- c("167 + 333", "667 + 1,333", "1,667 + 3,333",
         "3,333 + 6,667", "6,667 + 13,333", "16,667 + 33,333")
sizes <- c(500, 2000, 5000, 10000, 20000, 50000)

## A cell is the median across instances, with the quartiles beside it in the
## same unit. One instance has no spread to report, and says so in the caption
## rather than in a bracket that would look like one.
fmt_cell <- function(pkg, n) {
  r <- scaling[scaling$n_total == n & scaling$package == pkg, ]
  if (nrow(r) == 0) return("not run")
  if (is.na(r$median_s[1])) {
    st <- r$status[1]
    return(if (grepl("timeout", st)) "timeout"
           else if (grepl("overflow", st) || grepl("2^31", st, fixed = TRUE)) "int overflow"
           else "error")
  }
  in_ms <- r$median_s[1] < 1
  d <- function(x) if (in_ms) sprintf("%.0f", 1000 * x) else sprintf("%.3g", x)
  core <- paste0(d(r$median_s[1]), if (in_ms) " ms" else " s")
  if (isTRUE(r$instances[1] >= 2L)) {
    paste0(core, " (", d(r$q25_s[1]), "-", d(r$q75_s[1]), ")")
  } else {
    core
  }
}
fmt <- function(pkg) vapply(sizes, function(n) fmt_cell(pkg, n), character(1))

inst <- vapply(sizes, function(n) {
  r <- scaling[scaling$n_total == n & scaling$package == "couplr", ]
  if (nrow(r) == 0) NA_integer_ else as.integer(r$instances[1])
}, integer(1))
single <- sizes[!is.na(inst) & inst < 2]

tab <- data.frame(
  `Problem size` = lab,
  couplr   = fmt("couplr"),
  optmatch = fmt("optmatch"),
  MatchIt  = fmt("MatchIt"),
  check.names = FALSE
)

single_txt <- if (length(single) == 1) {
  sprintf("The %s row carries one instance and is a single run rather than a median, so no range is reported for it.",
          format(single, big.mark = ","))
} else if (length(single) > 1) {
  sprintf("The %s rows carry one instance each and are single runs rather than medians, so no range is reported for them.",
          paste(format(single, big.mark = ","), collapse = " and "))
} else {
  ""
}

knitr::kable(
  tab, align = "lrrr", booktabs = TRUE,
  caption = paste(
    "One-to-one optimal Mahalanobis matching, wall-clock time by problem size. Treated to control ratio 1:2, eight covariates, pooled within-group covariance, single core with single-threaded BLAS on an Apple M4 Pro. Each cell is the median over independently generated instances of that size, with the interquartile range across instances in brackets and the timing repetitions taken inside each instance.",
    single_txt,
    "The optmatch option max.problem.size was set to Inf for the two largest sizes. int overflow marks an integer-size overflow inside the optmatch back end reached through MatchIt; timeout marks a run exceeding the 600-second cap.")
)


## ----capability, echo=FALSE---------------------------------------------------
cap <- data.frame(
  Feature = c("Per-variable calipers from a named vector",
              "Rectangular problems without padding",
              "Sparse cost support",
              "k-best assignments",
              "Bottleneck (minimax) assignment",
              "Rosenbaum sensitivity bounds",
              "Dual potentials and optimality certificate",
              "User-selectable assignment algorithm"),
  couplr = c("yes", "yes", "yes", "yes", "yes", "yes", "yes", "19 solvers"),
  MatchIt = c("yes", "via padding", "no", "no", "no", "no", "no",
              "via optmatch"),
  optmatch = c("partial", "via padding", "yes", "no", "no", "no", "no",
               "5 algorithms"),
  check.names = FALSE
)
knitr::kable(
  cap, align = "lccc", booktabs = TRUE,
  caption = "Selected assignment-layer features, omitting areas where the alternatives lead, among them the breadth of designs reachable through a single MatchIt call and the maturity of optmatch's full matching. optmatch's calipers threshold one distance object at a time, so a per-variable set requires combining objects, and both alternatives reach the solver as a padded or variable-ratio formulation rather than as a rectangular cost matrix. The certificate row records whether a package exports a function returning duals or verifying optimality, which neither does: optmatch attaches its flow solver's node prices to a fullmatch() result in an undocumented MCFSolutions attribute, and the function evaluating the primal against them is internal. That row was assessed on 2026-08-26 and the others on 2026-08-09, both against MatchIt 4.7.2 and optmatch 0.10.8."
)

