// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lap_prepare_cost_matrix
Rcpp::List lap_prepare_cost_matrix(NumericMatrix cost, bool maximize);
RcppExport SEXP _assignr_lap_prepare_cost_matrix(SEXP costSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_prepare_cost_matrix(cost, maximize));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_bruteforce
Rcpp::List lap_solve_bruteforce(NumericMatrix cost, bool maximize);
RcppExport SEXP _assignr_lap_solve_bruteforce(SEXP costSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_bruteforce(cost, maximize));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_jv
Rcpp::List lap_solve_jv(NumericMatrix cost, bool maximize);
RcppExport SEXP _assignr_lap_solve_jv(SEXP costSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_jv(cost, maximize));
    return rcpp_result_gen;
END_RCPP
}
// lap_kbest_murty
Rcpp::List lap_kbest_murty(Rcpp::NumericMatrix cost, int k, bool maximize, std::string single_method);
RcppExport SEXP _assignr_lap_kbest_murty(SEXP costSEXP, SEXP kSEXP, SEXP maximizeSEXP, SEXP single_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type single_method(single_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_kbest_murty(cost, k, maximize, single_method));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_auction
Rcpp::List lap_solve_auction(Rcpp::NumericMatrix cost, bool maximize, Rcpp::Nullable<double> eps);
RcppExport SEXP _assignr_lap_solve_auction(SEXP costSEXP, SEXP maximizeSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_auction(cost, maximize, eps));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_auction_scaled
Rcpp::List lap_solve_auction_scaled(Rcpp::NumericMatrix cost, bool maximize, std::string schedule);
RcppExport SEXP _assignr_lap_solve_auction_scaled(SEXP costSEXP, SEXP maximizeSEXP, SEXP scheduleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type schedule(scheduleSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_auction_scaled(cost, maximize, schedule));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_auction_gs
Rcpp::List lap_solve_auction_gs(Rcpp::NumericMatrix cost, bool maximize, Rcpp::Nullable<double> eps);
RcppExport SEXP _assignr_lap_solve_auction_gs(SEXP costSEXP, SEXP maximizeSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_auction_gs(cost, maximize, eps));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_ssp
Rcpp::List lap_solve_ssp(Rcpp::NumericMatrix cost, bool maximize);
RcppExport SEXP _assignr_lap_solve_ssp(SEXP costSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_ssp(cost, maximize));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_hungarian
Rcpp::List lap_solve_hungarian(Rcpp::NumericMatrix cost, bool maximize);
RcppExport SEXP _assignr_lap_solve_hungarian(SEXP costSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_hungarian(cost, maximize));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_csflow
Rcpp::List lap_solve_csflow(Rcpp::NumericMatrix cost, bool maximize);
RcppExport SEXP _assignr_lap_solve_csflow(SEXP costSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_csflow(cost, maximize));
    return rcpp_result_gen;
END_RCPP
}
// lap_kbest_lawler
Rcpp::List lap_kbest_lawler(Rcpp::NumericMatrix cost, int k, std::string method_base, bool maximize);
RcppExport SEXP _assignr_lap_kbest_lawler(SEXP costSEXP, SEXP kSEXP, SEXP method_baseSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method_base(method_baseSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_kbest_lawler(cost, k, method_base, maximize));
    return rcpp_result_gen;
END_RCPP
}
// lap_solve_hk01
Rcpp::List lap_solve_hk01(Rcpp::NumericMatrix cost, bool maximize);
RcppExport SEXP _assignr_lap_solve_hk01(SEXP costSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lap_solve_hk01(cost, maximize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_assignr_lap_prepare_cost_matrix", (DL_FUNC) &_assignr_lap_prepare_cost_matrix, 2},
    {"_assignr_lap_solve_bruteforce", (DL_FUNC) &_assignr_lap_solve_bruteforce, 2},
    {"_assignr_lap_solve_jv", (DL_FUNC) &_assignr_lap_solve_jv, 2},
    {"_assignr_lap_kbest_murty", (DL_FUNC) &_assignr_lap_kbest_murty, 4},
    {"_assignr_lap_solve_auction", (DL_FUNC) &_assignr_lap_solve_auction, 3},
    {"_assignr_lap_solve_auction_scaled", (DL_FUNC) &_assignr_lap_solve_auction_scaled, 3},
    {"_assignr_lap_solve_auction_gs", (DL_FUNC) &_assignr_lap_solve_auction_gs, 3},
    {"_assignr_lap_solve_ssp", (DL_FUNC) &_assignr_lap_solve_ssp, 2},
    {"_assignr_lap_solve_hungarian", (DL_FUNC) &_assignr_lap_solve_hungarian, 2},
    {"_assignr_lap_solve_csflow", (DL_FUNC) &_assignr_lap_solve_csflow, 2},
    {"_assignr_lap_kbest_lawler", (DL_FUNC) &_assignr_lap_kbest_lawler, 4},
    {"_assignr_lap_solve_hk01", (DL_FUNC) &_assignr_lap_solve_hk01, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_assignr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
