suppressPackageStartupMessages(library(microbenchmark))
pkgload::load_all(".", quiet = TRUE)
set.seed(42)
n <- 200L
cost <- matrix(sample.int(10000L, n*n, replace=TRUE), n, n)
cat("network_simplex warm-up...\n"); flush.console()
invisible(assignment(cost, method="network_simplex"))
cat("microbenchmark 5 reps...\n"); flush.console()
mb <- microbenchmark(assignment(cost, method="network_simplex"), times=5L, unit="ms")
cat("median:", summary(mb)$median, "ms\n"); flush.console()
